# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- develop
- feature/*
- bugfix/*

pool:
  name: 'Demo'
  artifaceName: drop

variables:
  config: 'Release'

stages:
- stage: 'Build'
  jobs:
  - job: 'DockerBuild'
    steps:  
    - task: Npm@1
      displayName: 'Install Client Dependencies'

- stage: 'DevDeployment'
  jobs:
    # Track deployments on the environment.
  - deployment: DeployWeb
    displayName: 'deploy Web App'



- stage: 'TestDeployment'
  jobs:
    # Track deployments on the environment.
  - deployment: DeployWeb
    displayName: 'deploy Web App'
 

- stage: 'StagingDeployment'
  jobs:
    # Track deployments on the environment.
  - deployment: DeployWeb
    displayName: 'deploy Web App'
    variables: 
      app: bermtecstaging


- stage: 'ProdDeployment'
  jobs:
    # Track deployments on the environment.
  - deployment: DeployWeb
    displayName: 'deploy Web App'
    condition: and(succeeded(), eq(variables.isMain, 'true'))
    variables: 
      app: bermtec
